/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./app/**/*.{js,jsx}",
    "./components/**/*.{js,jsx}",
    "./lib/**/*.{js,jsx}",
    "./hooks/**/*.{js,jsx}",
    "./utils/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      screens: {
        "2xl": "1536px",
        "3xl": "1920px",
        "4xl": "2560px",
      },
      maxWidth: {
        "8xl": "88rem",
        "9xl": "96rem",
        "10xl": "104rem",
      },
      container: {
        center: true,
        padding: {
          DEFAULT: "1rem",
          sm: "2rem",
          lg: "4rem",
          xl: "5rem",
          "2xl": "6rem",
          "3xl": "8rem",
        },
        screens: {
          sm: "640px",
          md: "768px",
          lg: "1024px",
          xl: "1280px",
          "2xl": "1536px",
          "3xl": "1920px",
        },
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          5: "var(--color-primary-5)",
          10: "var(--color-primary-10)",
          20: "var(--color-primary-20)",
          30: "var(--color-primary-30)",
          40: "var(--color-primary-40)",
          50: "var(--color-primary-50)",
          60: "var(--color-primary-60)",
          70: "var(--color-primary-70)",
          80: "var(--color-primary-80)",
          90: "var(--color-primary-90)",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        lime: {
          5: "var(--color-lime-5)",
          10: "var(--color-lime-10)",
          20: "var(--color-lime-20)",
          30: "var(--color-lime-30)",
          40: "var(--color-lime-40)",
          50: "var(--color-lime-50)",
          60: "var(--color-lime-60)",
          70: "var(--color-lime-70)",
          80: "var(--color-lime-80)",
          90: "var(--color-lime-90)",
        },
        orange: {
          5: "var(--color-orange-5)",
          10: "var(--color-orange-10)",
          20: "var(--color-orange-20)",
          30: "var(--color-orange-30)",
          40: "var(--color-orange-40)",
          50: "var(--color-orange-50)",
          60: "var(--color-orange-60)",
          70: "var(--color-orange-70)",
          80: "var(--color-orange-80)",
          90: "var(--color-orange-90)",
        },
        purple: {
          5: "var(--color-purple-5)",
          10: "var(--color-purple-10)",
          20: "var(--color-purple-20)",
          30: "var(--color-purple-30)",
          40: "var(--color-purple-40)",
          50: "var(--color-purple-50)",
          60: "var(--color-purple-60)",
          70: "var(--color-purple-70)",
          80: "var(--color-purple-80)",
          90: "var(--color-purple-90)",
        },
        font: {
          h2: "var(--color-font-h2)",
          "h2-5": "var(--color-font-h2-5)",
        },
        danger: {
          5: "var(--color-danger-5)",
          10: "var(--color-danger-10)",
          20: "var(--color-danger-20)",
          30: "var(--color-danger-30)",
          40: "var(--color-danger-40)",
          50: "var(--color-danger-50)",
          60: "var(--color-danger-60)",
          70: "var(--color-danger-70)",
          80: "var(--color-danger-80)",
          90: "var(--color-danger-90)",
        },
        warning: {
          5: "var(--color-warning-5)",
          10: "var(--color-warning-10)",
          20: "var(--color-warning-20)",
          30: "var(--color-warning-30)",
          40: "var(--color-warning-40)",
          50: "var(--color-warning-50)",
          60: "var(--color-warning-60)",
          70: "var(--color-warning-70)",
          80: "var(--color-warning-80)",
          90: "var(--color-warning-90)",
        },
        success: {
          5: "var(--color-success-5)",
          10: "var(--color-success-10)",
          20: "var(--color-success-20)",
          30: "var(--color-success-30)",
          40: "var(--color-success-40)",
          50: "var(--color-success-50)",
          60: "var(--color-success-60)",
          70: "var(--color-success-70)",
          80: "var(--color-success-80)",
          90: "var(--color-success-90)",
        },
        info: {
          5: "var(--color-info-5)",
          10: "var(--color-info-10)",
          20: "var(--color-info-20)",
          30: "var(--color-info-30)",
          40: "var(--color-info-40)",
          50: "var(--color-info-50)",
          60: "var(--color-info-60)",
          70: "var(--color-info-70)",
          80: "var(--color-info-80)",
          90: "var(--color-info-90)",
        },
        lime: {
          5: "var(--color-lime-5)",
          10: "var(--color-lime-10)",
          20: "var(--color-lime-20)",
          30: "var(--color-lime-30)",
          40: "var(--color-lime-40)",
          50: "var(--color-lime-50)",
          60: "var(--color-lime-60)",
          70: "var(--color-lime-70)",
          80: "var(--color-lime-80)",
          90: "var(--color-lime-90)",
        },
        orange: {
          5: "var(--color-orange-5)",
          10: "var(--color-orange-10)",
          20: "var(--color-orange-20)",
          30: "var(--color-orange-30)",
          40: "var(--color-orange-40)",
          50: "var(--color-orange-50)",
          60: "var(--color-orange-60)",
          70: "var(--color-orange-70)",
          80: "var(--color-orange-80)",
          90: "var(--color-orange-90)",
        },
        // gray: {
        //   0: "var(--color-gray-0)",
        //   5: "var(--color-gray-5)",
        //   10: "var(--color-gray-10)",
        //   20: "var(--color-gray-20)",
        //   30: "var(--color-gray-30)",
        //   40: "var(--color-gray-40)",
        //   50: "var(--color-gray-50)",
        //   60: "var(--color-gray-60)",
        //   70: "var(--color-gray-70)",
        //   80: "var(--color-gray-80)",
        //   90: "var(--color-gray-90)",
        //   100: "var(--color-gray-100)",
        //   secondary: "var(--color-gray-secondary)",
        // },
        border: {
          gray: "var(--color-border-gray)",
        },
      },

      /* Typography Scale */
      fontSize: {
        xss: "var(--font-size-xxs)",
        xs: "var(--font-size-xs)",
        sm: "var(--font-size-sm)",
        base: "var(--font-size-base)",
        lg: "var(--font-size-lg)",
        xl: "var(--font-size-xl)",
        "2xl": "var(--font-size-2xl)",
        "3xl": "var(--font-size-3xl)",
        "4xl": "var(--font-size-4xl)",
        "5xl": "var(--font-size-5xl)",
        "6xl": "var(--font-size-6xl)",
      },

      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
