// Logo mapping for different media outlets
const logoMap = {
  "businessinsider.com": "/assets/logos/business-insider.png",
  "bloomberg.com": "/assets/logos/bloomberg.jpg",
  "wsj.com": "/assets/logos/wsj.jpg",
  "finance.yahoo.com": "/assets/logos/yahoo.png",
  "marketwatch.com": "/assets/logos/marketwatch.png",
  "reuters.com": "/assets/logos/reuters.png",
  "apnews.com": "/assets/logos/ap-news.png",
  "theglobeandmail.com": "/assets/logos/globe-and-mail.png",
  "financialpost.com": "/assets/logos/financial-post.png",
  "ceo.ca": "/assets/logos/ceo-ca.png",
  "stockhouse.com": "/assets/logos/stockhouse.jpg",
  "streetinsider.com": "/assets/logos/street-insider.png",
  "apple.com": "/assets/logos/apple-news.png",
  "digitaljournal.com": "/assets/logos/digital-journal.jpg",
  "prospectornews.com": "/assets/logos/prospector-news.png",
  "dowjones.com": "/assets/logos/dow-jones.png",
  "lexisnexis.com": "/assets/logos/lexis-nexis.png",
  "thomsonreuters.com": "/assets/logos/reuters.png",
  "finanznachrichten.de": "/assets/logos/finanznachrichten.png",
  "centralcharts.com": "/assets/logos/centralcharts.png",
  "x.com": "/assets/logos/x-logo.png",
  "accern.com": "/assets/logos/accern.png",
  "comtex.com": "/assets/logos/comtex.png",
  "newsbank.com": "/assets/logos/newsbank.png",
  "postmedia.com": "/assets/logos/postmedia.png",
  "newsware.com": "/assets/logos/newsware.png",
  "insidertracking.com": "/assets/logos/ink-research.png",
  "infodesk.com": "/assets/logos/infodesk.png",
  "newsedge.com": "/assets/logos/moodys.png",
  "factiva.com": "/assets/logos/factiva.png",
  "crweworld.com": "/assets/logos/crwe.png",
  "quotemedia.com": "/assets/logos/quotemedia.png",
  "gale.com": "/assets/logos/gale.png",
  "newstex.com": "/assets/logos/newstex.png",
  "teletrader.com": "/assets/logos/teletrader.png",
  "theprospectornews.com": "/assets/logos/prospector-news.png",
  "sentieo.com": "/assets/logos/sentieo.png",
  "ad-hoc-news.de": "/assets/logos/ad-hoc-news.png",
  "beautytipa.com": "/assets/logos/beautytipa.png",
  "creatework.com": "/assets/logos/creatework.png",
  "eco-natur.com": "/assets/logos/eco-natur.png",
  "fitnesseditors.com": "/assets/logos/fitnesseditors.png",
  "motor-world.com": "/assets/logos/motor-world.png",
  "usa-update.com": "/assets/logos/usa-update.png",
  "usanew.biz": "/assets/logos/usanew.png",
  "whatbiz.co": "/assets/logos/whatbiz.png",
  "xdzee.com": "/assets/logos/xdzee.png",
  "agricharts.com": "/assets/logos/agricharts.png",
  "ambickley.com": "/assets/logos/ambickley.png",
  "bierigrain.com": "/assets/logos/bierigrain.png",
  "burlingtonok.com": "/assets/logos/burlington.png",
  "cfgag.net": "/assets/logos/cfgag.png",
  "flatlandsgrain.com": "/assets/logos/flatlands.png",
  "geraldgrain.com": "/assets/logos/gerald.png",
  "7riverslivestock.com": "/assets/logos/7rivers.png",
  "agbest.com": "/assets/logos/agbest.png",
  "agrail.com": "/assets/logos/agrail.png",
  "agrowstar.com": "/assets/logos/agrowstar.png",
  "agsouthwest.com": "/assets/logos/agsouthwest.png",
  "antoncoop.com": "/assets/logos/antoncoop.png",
  "arabigin.com": "/assets/logos/arabigin.png",
  "augustafarmers.com": "/assets/logos/augustafarmers.png",
  "bannercoop.net": "/assets/logos/bannercoop.png",
  "bar-g.com": "/assets/logos/bar-g.png",
  "beardsleyfe.com": "/assets/logos/beardsleyfe.png",
  "bloomingtonlivestock.com": "/assets/logos/bloomington.png",
  "boltmarketingllc.com": "/assets/logos/boltmarketing.png",
  "brtagandturf.net": "/assets/logos/brtagandturf.png",
  "butterfieldgrain.com": "/assets/logos/butterfield.png",
  "cainagra.net": "/assets/logos/cainagra.png",
  "camerongrain.com": "/assets/logos/camerongrain.png",
  "cdrfarmsllc.com": "/assets/logos/cdrfarms.png",
  "centralplainstrading.com": "/assets/logos/centralplains.png",
  "cgsmc.com": "/assets/logos/cgsmc.png",
  "cherokeegin.com": "/assets/logos/cherokeegin.png",
  "claremarfarms.com": "/assets/logos/claremarfarms.png",
  "coopservicesinc.com": "/assets/logos/coopservices.png",
  "craiggrain.com": "/assets/logos/craiggrain.png",
  "dacomacoop.com": "/assets/logos/dacomacoop.png",
  "dixongin.com": "/assets/logos/dixongin.png",
  "doerungin.com": "/assets/logos/doerungin.png",
  "doonelevator.com": "/assets/logos/doonelevator.png",
  "dumascoop.com": "/assets/logos/dumascoop.png",
  "dummersgrain.com": "/assets/logos/dummersgrain.png",
  "edonfarmerscoop.com": "/assets/logos/edonfarmerscoop.png",
  "eldoradocoop.yourgin.com": "/assets/logos/eldoradocoop.png",
  "carnegiecoop.com": "/assets/logos/carnegiecoop.png",
  "lfdfarmers.com": "/assets/logos/lfdfarmers.png",
  "farmerscoopelevator.com": "/assets/logos/farmerscoopelevator.png",
  "farmersexchangecoop.com": "/assets/logos/farmersexchange.png",
  "farmersgrainelevator.com": "/assets/logos/farmersgrainelevator.png",
  "frenchcampgrain.com": "/assets/logos/frenchcampgrain.png",
  "glendenninggrainandsoil.com": "/assets/logos/glendenninggrain.png",
  "gocoopok.com": "/assets/logos/gocoopok.png",
  "gowanlea.com": "/assets/logos/gowanlea.png",
  "greencitylivestock.com": "/assets/logos/greencitylivestock.png",
  "hbspecialties.com": "/assets/logos/hbspecialties.png",
  "hullfeed.com": "/assets/logos/hullfeed.png",
  "intermountainbeef.com": "/assets/logos/intermountainbeef.png",
  "investorsics.net": "/assets/logos/investorsics.png",
  "jamesvalleygrain.com": "/assets/logos/jamesvalleygrain.png",
  "jlyngrains.com": "/assets/logos/jlyngrains.png",
  "judgefarms.com": "/assets/logos/judgefarms.png",
  "kellergrain.com": "/assets/logos/kellergrain.png",
  "langfarms.com": "/assets/logos/langfarms.png",
  "leroycoop.coop": "/assets/logos/leroycoop.png",
  "lesyoungfarms.com": "/assets/logos/lesyoungfarms.png",
  "lickelevator.com": "/assets/logos/lickelevator.png",
  "littlesiouxcornprocessors.com": "/assets/logos/littlesiouxcorn.png",
  "lubbockfeeders.com": "/assets/logos/lubbockfeeders.png",
  "mccunecoop.com": "/assets/logos/mccunecoop.png",
  "melrosefarmservice.com": "/assets/logos/melrosefarmservice.png",
  "mcin.biz": "/assets/logos/mcin.png",
  "midvalleycottongrowers.com": "/assets/logos/midvalleycottongrowers.png",
  "mobleygin.com": "/assets/logos/mobleygin.png",
  "montrosegrain.com": "/assets/logos/montrosegrain.png",
  "morganvillecoop.com": "/assets/logos/morganvillecoop.png",
  "mulvanecoop.com": "/assets/logos/mulvanecoop.png",
  "nwinvestmentsllc.com": "/assets/logos/nwinvestments.png",
  "offerle.coop": "/assets/logos/offerlecoop.png",
  "oklandruncoop.net": "/assets/logos/oklandruncoop.png",
  "omegafarmsupply.com": "/assets/logos/omegafarmsupply.png",
  "parrishshop.com": "/assets/logos/parrishshop.png",
  "pcefloydada.com": "/assets/logos/pcefloydada.png",
  "petersencustomfarming.ca": "/assets/logos/petersencustomfarming.png",
  "pilotgrovecoop.com": "/assets/logos/pilotgrovecoop.png",
  "premiumfeedgrain.com": "/assets/logos/premiumfeedgrain.png",
  "proagfarmers.com": "/assets/logos/proagfarmers.png",
  "punkincentergin.com": "/assets/logos/punkincentergin.png",
  "remsencoop.com": "/assets/logos/remsencoop.png",
  "rickettgrain.com": "/assets/logos/rickettgrain.png",
  "ringneckenergy.com": "/assets/logos/ringneckenergy.png",
  "rollingacresgrain.com": "/assets/logos/rollingacresgrain.png",
  "rollinghillsgin.com": "/assets/logos/rollinghillsgin.png",
  "sandbcattle.com": "/assets/logos/sandbcattle.png",
  "sargeantgrain.com": "/assets/logos/sargeantgrain.png",
  "schrammfeedlot.net": "/assets/logos/schrammfeedlot.png",
  "shcommodities.com": "/assets/logos/shcommodities.png",
  "silveredgecoop.com": "/assets/logos/silveredgecoop.png",
  "snyderfarmerscoop.com": "/assets/logos/snyderfarmerscoop.png",
  "sowegacotton.com": "/assets/logos/sowegacotton.png",
  "scfmco.com": "/assets/logos/scfmco.png",
  "stickneyelevator.com": "/assets/logos/stickneyelevator.png",
  "stonestationelevator.com": "/assets/logos/stonestationelevator.png",
  "stoneybrookelevators.ca": "/assets/logos/stoneybrookelevators.png",
  "straussfeedmill.com": "/assets/logos/straussfeedmill.png",
  "tcgrain.com": "/assets/logos/tcgrain.png",
  "texasproducerscoop.com": "/assets/logos/texasproducerscoop.png",
  "thefarmerselevator.com": "/assets/logos/thefarmerselevator.png",
  "theinsuranceshopinc.com": "/assets/logos/theinsuranceshopinc.png",
  "tremont.coop": "/assets/logos/tremontcoop.png",
  "triplemfarms.us": "/assets/logos/triplemfarms.png",
  "trotterinc.com": "/assets/logos/trotterinc.png",
  "turnerseedinc.com": "/assets/logos/turnerseedinc.png",
  "turonmill.com": "/assets/logos/turonmill.png",
  "underwoodgrain.com": "/assets/logos/underwoodgrain.png",
  "uvaldecoop.com": "/assets/logos/uvaldecoop.png",
  "waittgrain.com": "/assets/logos/waittgrain.png",
  "walterscoop.com": "/assets/logos/walterscoop.png",
  "westco.coop": "/assets/logos/westco.png",
  "bigspringherald.com": "/assets/logos/bigspringherald.png",
  "dailytimesleader.com": "/assets/logos/dailytimesleader.png",
  "decaturdailydemocrat.com": "/assets/logos/decaturdailydemocrat.png",
  "dptribune.com": "/assets/logos/dptribune.png",
  "inyoregister.com": "/assets/logos/inyoregister.png",
  "kanerepublican.com": "/assets/logos/kanerepublican.png",
  "mammothtimes.com": "/assets/logos/mammothtimes.png",
  "minstercommunitypost.com": "/assets/logos/minstercommunitypost.png",
  "observernewsonline.com": "/assets/logos/observernewsonline.png",
  "poteaudailynews.com": "/assets/logos/poteaudailynews.png",
  "punxsutawneyspirit.com": "/assets/logos/punxsutawneyspirit.png",
  "ridgwayrecord.com": "/assets/logos/ridgwayrecord.png",
  "starkvilledailynews.com": "/assets/logos/starkvilledailynews.png",
  "sweetwaterreporter.com": "/assets/logos/sweetwaterreporter.png",
  "theantlersamerican.com": "/assets/logos/theantlersamerican.png",
  "theeveningleader.com": "/assets/logos/theeveningleader.png",
  "thepilotnews.com": "/assets/logos/thepilotnews.png",
  "times-online.com": "/assets/logos/times-online.png",
  "wapakdailynews.com": "/assets/logos/wapakdailynews.png",
  "chroniclejournal.com": "/assets/logos/chroniclejournal.png",
  "avpress.marketminute.com": "/assets/logos/avpress.png",
  "bakersfield.marketminute.com": "/assets/logos/bakersfield.png",
  "am-news.com": "/assets/logos/am-news.png",
  "borgernewsherald.com": "/assets/logos/borgernewsherald.png",
  "bostonherald.com": "/assets/logos/bostonherald.png",
  "bpas.com": "/assets/logos/bpas.png",
  "buffnews.com": "/assets/logos/buffnews.png",
  "burlingame.com": "/assets/logos/burlingame.png",
  "cortemadera.com": "/assets/logos/cortemadera.png",
  "custercountychief.com": "/assets/logos/custercountychief.png",
  "dalycity.com": "/assets/logos/dalycity.png",
  "fatpitch.financials": "/assets/logos/fatpitch.png",
  "1discountbrokerage.com": "/assets/logos/1discountbrokerage.png",
  "fwnbc.com": "/assets/logos/fwnbc.png",
  "fox47.com": "/assets/logos/fox47.png",
  "franklincredit.com": "/assets/logos/franklincredit.png",
  "gafri.com": "/assets/logos/gafri.png",
  "hannibal.marketminute.com": "/assets/logos/hannibal.png",
  "whig.com": "/assets/logos/whig.png",
  "ibtimes.com": "/assets/logos/ibtimes.png",
  "ivpressonline.marketminute.com": "/assets/logos/ivpressonline.png",
  "kbjr.marketminute.com": "/assets/logos/kbjr.png",
  "ktiv.com": "/assets/logos/ktiv.png",
  "kttc.com": "/assets/logos/kttc.png",
  "kvoa.com": "/assets/logos/kvoa.png",
  "kwwl.com": "/assets/logos/kwwl.png",
  "livermore.com": "/assets/logos/livermore.png",
  "lodinews.com": "/assets/logos/lodinews.png",
  "losaltos.com": "/assets/logos/losaltos.png",
  "malvern-online.com": "/assets/logos/malvern-online.png",
  "menlopark.com": "/assets/logos/menlopark.png",
  "millvalley.com": "/assets/logos/millvalley.png",
  "mtrustcompany.marketminute.com": "/assets/logos/mtrustcompany.png",
  "mymotherlode.com": "/assets/logos/mymotherlode.png",
  "newsok.com": "/assets/logos/newsok.png",
  "pentictonherald.com": "/assets/logos/pentictonherald.png",
  "postgazette.com": "/assets/logos/postgazette.png",
  "pleasanton.com": "/assets/logos/pleasanton.png",
  "recorderonline.marketminute.com": "/assets/logos/recorderonline.png",
  "presstelegram.com": "/assets/logos/presstelegram.png",
  "bentoncourier.com": "/assets/logos/bentoncourier.png",
  "sananselmo.com": "/assets/logos/sananselmo.png",
  "sandiego.com": "/assets/logos/sandiego.png",
  "sanrafael.com": "/assets/logos/sanrafael.png",
  "santaclara.com": "/assets/logos/santaclara.png",
  "santamariatimes.marketminute.com": "/assets/logos/santamariatimes.png",
  "sausalito.com": "/assets/logos/sausalito.png",
  "sdgnewsgroup.marketminute.com": "/assets/logos/sdgnewsgroup.png",
  "spoke.com": "/assets/logos/spoke.png",
  "startribune.com": "/assets/logos/startribune.png",
  "sunnyvale.com": "/assets/logos/sunnyvale.png",
  "tamarsecurities.com": "/assets/logos/tamarsecurities.png",
  "appeal-democrat.marketminute.com": "/assets/logos/appeal-democrat.png",
  "kelownadailycourier.com": "/assets/logos/kelownadailycourier.png",
  "newportvermontdailyexpress.com":
    "/assets/logos/newportvermontdailyexpress.png",
  "thesunchronicle.marketminute.com": "/assets/logos/thesunchronicle.png",
  "uniondemocrat.marketminute.com": "/assets/logos/uniondemocrat.png",
  "thewesterlysun.marketminute.com": "/assets/logos/thewesterlysun.png",
  "thnews.marketminute.com": "/assets/logos/thnews.png",
  "townhall.com": "/assets/logos/townhall.png",
  "fatpitch.valueinvestingnews": "/assets/logos/fatpitchvalueinvestingnews.png",
  "wss.com": "/assets/logos/wss.png",
  "walnutcreekguide.com": "/assets/logos/walnutcreekguide.png",
  "waow.com": "/assets/logos/waow.png",
  "wbng.com": "/assets/logos/wbng.png",
  "week.com": "/assets/logos/week.png",
  "wgem.com": "/assets/logos/wgem.png",
  "winslow.com": "/assets/logos/winslow.png",
  "wkow.com": "/assets/logos/wkow.png",
  "wpta.com": "/assets/logos/wpta.png",
  "wqow.com": "/assets/logos/wqow.png",
  "wral.com": "/assets/logos/wral.png",
  "wrex.com": "/assets/logos/wrex.png",
  "wsil.com": "/assets/logos/wsil.png",
  "wvva.com": "/assets/logos/wvva.png",
  "wxow.com": "/assets/logos/wxow.png",
  "ontariofarmer.com": "/assets/logos/ontariofarmer.png",
  "princegeorgepost.com": "/assets/logos/princegeorgepost.png",
  "airdrieecho.com": "/assets/logos/airdrieecho.png",
  "intelligencer.ca": "/assets/logos/intelligencer.png",
  "thecragandcanyon.ca": "/assets/logos/thecragandcanyon.png",
  "brantfordexpositor.ca": "/assets/logos/brantfordexpositor.png",
  "recorder.ca": "/assets/logos/recorder.png",
  "chathamdailynews.ca": "/assets/logos/chathamdailynews.png",
  "chathamthisweek.com": "/assets/logos/chathamthisweek.png",
  "clintonnewsrecord.com": "/assets/logos/clintonnewsrecord.png",
  "cochranetimespost.ca": "/assets/logos/cochranetimespost.png",
  "cochranetimes.com": "/assets/logos/cochranetimes.png",
  "coldlakesun.com": "/assets/logos/coldlakesun.png",
  "standard-freeholder.com": "/assets/logos/standard-freeholder.png",
  "calgaryherald.com": "/assets/logos/calgary-herald.png",
  "calgarysun.com": "/assets/logos/calgary-sun.png",
  "montrealgazette.com": "/assets/logos/montreal-gazette.png",
  "canada.com": "/assets/logos/canada.png",
  "canoe.com": "/assets/logos/canoe.png",
  "edmontonjournal.com": "/assets/logos/edmonton-journal.png",
  "edmontonsun.com": "/assets/logos/edmonton-sun.png",
  "lfpress.com": "/assets/logos/london-free-press.png",
  "ottawasun.com": "/assets/logos/ottawa-sun.png",
  "leaderpost.com": "/assets/logos/leaderpost.png",
  "thestarphoenix.com": "/assets/logos/star-phoenix.png",
  "windsorstar.com": "/assets/logos/windsor-star.png",
  "winnipegsun.com": "/assets/logos/winnipeg-sun.png",
  "theprovince.com": "/assets/logos/the-province.png",
  "nationalpost.com": "/assets/logos/national-post.png",
  "ottawacitizen.com": "/assets/logos/ottawa-citizen.png",
  "vancouversun.com": "/assets/logos/vancouver-sun.png",
  "torontosun.com": "/assets/logos/toronto-sun.png",
};

export function getLogoForUrl(url) {
  if (!url) return "/assets/logos/placeholder.svg";

  try {
    const hostname = new URL(url).hostname.toLowerCase();

    // Check for exact matches first
    if (logoMap[hostname]) {
      return logoMap[hostname];
    }

    // Check for partial matches
    for (const [domain, logo] of Object.entries(logoMap)) {
      if (hostname.includes(domain) || domain.includes(hostname)) {
        return logo;
      }
    }

    // Return placeholder if no match found
    return "/assets/logos/placeholder.svg";
  } catch (error) {
    return "/assets/logos/placeholder.svg";
  }
}

export function getOutletName(url) {
  if (!url) return "Unknown Outlet";

  try {
    const hostname = new URL(url).hostname.toLowerCase();

    // Extract domain name without TLD
    const domainParts = hostname.split(".");
    if (domainParts.length >= 2) {
      return (
        domainParts[domainParts.length - 2].charAt(0).toUpperCase() +
        domainParts[domainParts.length - 2].slice(1)
      );
    }

    return hostname;
  } catch (error) {
    return "Unknown Outlet";
  }
}
