// Logo mapping for different media outlets

// Helper functions
export const getLogoForUrl = (url) => {
  // Extract domain from URL
  const domain = url
    .replace(/^https?:\/\//, "")
    .replace(/^www\./, "")
    .split("/")[0];

  // Find matching logo by domain
  for (const [outletName, logoPath] of Object.entries(logoMapping)) {
    if (
      outletName.toLowerCase().includes(domain.toLowerCase()) ||
      domain.toLowerCase().includes(outletName.toLowerCase())
    ) {
      return logoPath;
    }
  }

  return null;
};

export const getOutletName = (url) => {
  // Extract domain from URL
  const domain = url
    .replace(/^https?:\/\//, "")
    .replace(/^www\./, "")
    .split("/")[0];

  // Find matching outlet name by domain
  for (const [outletName, logoPath] of Object.entries(logoMapping)) {
    if (
      outletName.toLowerCase().includes(domain.toLowerCase()) ||
      domain.toLowerCase().includes(outletName.toLowerCase())
    ) {
      return outletName;
    }
  }

  return domain;
};

export const logoMapping = {
  "7 Rivers Livestock": "/website-logos/7riverslivestock.png",
  accern: "/website-logos/accern.jpg",
  "Ad Hoc News": "/website-logos/adhocnews.jpg",
  "AgBest Cooperative Inc.": "/website-logos/agbest.png",
  "AgRail LLC": "/website-logos/agrail.png",
  AGrowStar: "/website-logos/agrowstar.jpg",
  "Ag Southwest Crop & Ranch Insurance": "/website-logos/agsouthwest.png",
  "Antelope Valley Press": "/website-logos/antelope-valley-press.png",
  "Anton Co-op": "/website-logos/antoncoop.jpg",
  "Associated Press": "/website-logos/ap-logo.png",
  "Apple News": "/website-logos/apple-news.png",
  "Arabi Gin": "/website-logos/arabi.jpg",
  "Augusta Farmers Coop": "/website-logos/augustafarmers.png",
  "Bakersfield.com": "/website-logos/bakersfield.png",
  "Banner Co-operative Elevator Association": "/website-logos/bannercoop.png",
  "Bar-G Feedyard": "/website-logos/bar-g.png",
  "Barchart.com": "/website-logos/barchart.webp",
  "Beardsley Farmers Elevator Company": "/website-logos/beardsley.jpg",
  "beautytipa.com": "/website-logos/beautytipa.png",
  Benzinga: "/website-logos/benzinga.png",
  "Bingham News Chronicle": "/website-logos/bingham-news-chronicle.png",
  "Bloomberg Website": "/website-logos/bloomberg.jpg",
  "Bloomington Livestock Exchange": "/website-logos/bloomingtonlivestock.png",
  "Bolt Marketing LLC": "/website-logos/boltmarketingllc.png",
  "Borger News-Herald": "/website-logos/borger-news-herald.png",
  "Boston Herald": "/website-logos/boston-herald.svg",
  BPAS: "/website-logos/bpas.png",
  "BRT AG & TURF": "/website-logos/brtagandturf.png",
  "The Buffalo News": "/website-logos/buffalo-news.png",
  "Burlingame.com": "/website-logos/burlingame.png",
  "Business Insider": "/website-logos/business-insider.png",
  "Butterfield & Associates Grain": "/website-logos/butterfield.jpg",
  "Cain Agra": "/website-logos/cainagra.jpg",
  "Cameron Grain Corporation": "/website-logos/camerongrain.png",
  "CDR Farms, LLC": "/website-logos/cdr-farms.jpg",
  "Central Charts": "/website-logos/central-charts.png",
  "Central Plains Trading": "/website-logos/centralplainstrading.png",
  "CEO.CA": "/website-logos/ceo-ca.png",
  "Cooperative Grain and Supply": "/website-logos/cgsmc.png",
  "Cherokee Gin & Cotton Co. ": "/website-logos/cherokeegin.png",
  "Clare-Mar Farms Limited": "/website-logos/clare-mar.jpg",
  Comtex: "/website-logos/comtex.gif",
  "CO-OP Services, Inc.": "/website-logos/coop-services.jpg",
  "CorteMadera.com": "/website-logos/corte-madera.png",
  "Cunningham Farms, Inc.": "/website-logos/craiggrain.jpg",
  "creatework.com": "/website-logos/create-work.png",
  "CRWE World": "/website-logos/crweworld.png",
  "Custer County Chief": "/website-logos/custer-county-chief.jpg",
  "Dacoma Farmers Coop": "/website-logos/dacomacoop.png",
  "DalyCity.com": "/website-logos/daly-city.png",
  "Digital Journal": "/website-logos/digital-journal.jpg",
  "Dixon Gin Co., Inc.": "/website-logos/dixongin.png",
  "Doerun Gin Company": "/website-logos/doerungin.png",
  "Doon Elevator, Inc": "/website-logos/doonelevator.png",
  "Dow Jones Factiva": "/website-logos/dow-jones-factiva.png",

  "Dow Jones Newswires": "/website-logos/dow-jones-newswire.png",
  "Dumas Co-op Elevators": "/website-logos/dumas.jpg",
  "Dummer&#39;s Grain Service & Buck County Grain":
    "/website-logos/dummersgrain.png",
  "eco-natur.com": "/website-logos/econatur.png",

  "Edon Farmers Co-op": "/website-logos/edonfarmerscoop.jpg",
  "Farmers Cooperative Association of Eldorado":
    "/website-logos/farmers-coop-eldorado.jpg",
  "Farmers Coop Mill and Elevator - Carnegie":
    "/website-logos/farmers-coop-mill-elevator.png",
  "Litchfield Farmers Grain": "/website-logos/farmers-grain-litchfield.jpg",
  "Farmers Cooperative Elevator Co. MN Hanley Falls":
    "/website-logos/farmerscoopelevator.png",

  "Farmers Exchange": "/website-logos/farmersexchangecoop.jpg",
  "Farmers Grain Elevator": "/website-logos/farmersgrainelevator.png",
  "Fat Pitch Financials": "/website-logos/fat-pitch.png",
  FinanzNachrichten: "/website-logos/finanznachrichten1.gif",

  "1st Discount Brokerage": "/website-logos/first-discount-brokerage.jpg",
  "fitnesseditors.com": "/website-logos/fitnesseditors.png",

  "Fort Wayne": "/website-logos/fort-waynes.png",

  fox47: "/website-logos/fox47.jpg",
  "Franklin Credit Management Corporation":
    "/website-logos/franklin-credit.png",
  "French Camp Grain Company, Inc.": "/website-logos/frenchcampgrain.jpg",
  "Gale Cengage Learning": "/website-logos/gale-cengage.jpg",

  "Glendenning Grain": "/website-logos/glendenninggrainandsoil.jpg",
  "The Globe and Mail": "/website-logos/globeandmail.png",
  "Farmers Cooperative Association - Tonkawa, OK":
    "/website-logos/gocoopok.png",
  "Gowanlea LTD.": "/website-logos/gowanlea.jpg",

  "Great American Advisors": "/website-logos/great-american-advisors.png",
  "Green City Livestock Marketing, LLC":
    "/website-logos/greencitylivestock.png",
  "Hannibal Courier - Post": "/website-logos/hannibal.png",
  "H & B Specialties, Inc.": "/website-logos/hbspecialties.png",
  "Herald-Whig": "/website-logos/herald-whig.png",
  "Hull Feed & Produce, Inc": "/website-logos/hullfeed.png",

  "International Business Times": "/website-logos/ibt.png",
  "Imperial Valley Press": "/website-logos/imperial-valley-press.jpg",
  InfoDesk: "/website-logos/infodesk.png",
  "INK Research": "/website-logos/ink-research.png",
  "InterMountain Beef": "/website-logos/inner-mountain.jpg",

  "Investors Commodity Services": "/website-logos/investorsics.png",
  "James Valley Grain, LLC": "/website-logos/jamesvalleygrain.jpg",
  "J-LYN Grains": "/website-logos/jlyngrains.png",
  "Judge Farms": "/website-logos/judgefarms.png",
  "KBJR/CBS3": "/website-logos/kbjr6.png",

  "Keller Grain": "/website-logos/kellergrain.png",
  KTIV: "/website-logos/ktiv.png",
  KTTC: "/website-logos/kttc.png",
  KVOA: "/website-logos/kvoa.png",
  KWWL: "/website-logos/kwwl.png",

  "Lang Farms, Ltd.": "/website-logos/langfarms.png",
  "LeRoy Coop": "/website-logos/leroycoop.png",
  "Les Young Farms Ltd": "/website-logos/lesyoungfarms.jpg",
  "Lexis Nexis": "/website-logos/lexis-nexis.png",
  "Lick Elevator Inc.": "/website-logos/lick-elevator.jpg",
  "Little Sioux Corn Processors":
    "/website-logos/littlesiouxcornprocessors.png",

  "Livermore.com": "/website-logos/livermore.png",
  "lodinews.com": "/website-logos/lodinnews.jpg",

  "StreetInsider.com": "/website-logos/logo-street-insider.png",
  "LosAltos.com": "/website-logos/los-altos.png",
  "Lubbock Feeders": "/website-logos/lubbockfeeders.png",

  "Malvern Daily Record": "/website-logos/malvern-daily-record.jpg",
  Marketwatch: "/website-logos/marketwatch.png",
  "McCune Farmers Union Coop Association": "/website-logos/mccunecoop.png",
  "Melrose Farm Service Inc": "/website-logos/melrosefarmservice.png",
  "MenloPark.com": "/website-logos/menlo-park.png",
  "Mid-Columbia Insurance Inc.": "/website-logos/mid-columbia-insurance.jpg",

  "Mid-Valley Cotton Growers, Inc.": "/website-logos/mid-valley-cotton.jpg",
  "MillValley.com": "/website-logos/mill-valley.png",
  "Millennium Trust Company": "/website-logos/millennium-trust.png",
  "Mobley Gin Company": "/website-logos/mobleygin.png",

  "Montrose Grain and Supply, LLC": "/website-logos/montrosegrain.jpg",
  "Moody's Analytics NewsEdge": "/website-logos/moodys.png",
  "Farmers Coop Elevator - Morganville Coop":
    "/website-logos/morganvillecoop.jpg",
  "myMotherLode.com California Gold Country": "/website-logos/mother-loade.png",
  "motor-world.com": "/website-logos/motor-world.png",

  "Mulvane Cooperative Union": "/website-logos/mulvanecoop.jpg",
  NewsOK: "/website-logos/news-ok.png",
  Newsbank: "/website-logos/newsbank.png",
  Newsfile: "/website-logos/newsfile-small.jpg",
  Newstex: "/website-logos/newstex.png",
  Newsware: "/website-logos/newsware.png",
  "Northwest Investments": "/website-logos/nwinvestmentsllc.jpg",

  "Offerle Cooperative Grain & Supply Company": "/website-logos/offerle.png",
  "Land Run Farmers Cooperative - OK": "/website-logos/oklandruncoop.jpg",
  "Omega Farm Supply, Inc. & Gin Company": "/website-logos/omegafarmsupply.png",

  "Parrish Shop & Sales LLC": "/website-logos/parrishshop.png",
  "PCE Producers Coop Elevator": "/website-logos/pcefloydada.png",
  "Penticton Herald": "/website-logos/penticton-herald.jpg",
  "Petersen Custom Farming": "/website-logos/petersencustomfarming.png",

  "Pilot Grove Elevator Cooperative, Inc.": "/website-logos/pilotgrovecoop.png",
  "Pittsburgh Post-Gazette": "/website-logos/pittsburg-post.png",
  "Pleasanton.com": "/website-logos/pleasanton.png",
  "Calgary Herald": "/website-logos/pm-a-calgary-herald.svg",

  "Calgary Sun": "/website-logos/pm-a-calgary-sun.svg",
  "Canada.com": "/website-logos/pm-a-canada-dot-com.svg",
  "Canoe.com": "/website-logos/pm-a-canoe-dot-com.svg",
  "Edmonton Journal": "/website-logos/pm-a-edmonton-journal.svg",
  "Edmonton Sun": "/website-logos/pm-a-edmonton-sun.svg",
  "Financial Post": "/website-logos/pm-a-financial-post.svg",
  "London Free Press": "/website-logos/pm-a-london-free-press.svg",

  "National Post": "/website-logos/pm-a-national-post.svg",
  "Ontario Farmer": "/website-logos/pm-a-ontario-farmer.jpg",
  "Ottawa Citizen": "/website-logos/pm-a-ottawa-citizen.svg",
  "Ottawa Sun": "/website-logos/pm-a-ottawa-sun.svg",

  "Prince George Post": "/website-logos/pm-a-prince-george-post.svg",
  "Regina Leader Post": "/website-logos/pm-a-regina-leader-post.svg",
  "Saskatoon Star Phoenix": "/website-logos/pm-a-saskatoon-star-phoenix.svg",
  "Toronto Sun": "/website-logos/pm-a-toronto-sun.svg",

  "Windsor Star": "/website-logos/pm-a-windsor-star.svg",
  "Winnipeg Sun": "/website-logos/pm-a-winnipeg-sun.svg",
  "Montreal Gazette": "/website-logos/pm-aa-montreal-gazette.svg",
  "The Province": "/website-logos/pm-aa-province.svg",
  "Vancouver Sun": "/website-logos/pm-aa-vancouver-sun.svg",

  "Airdrie Echo": "/website-logos/pm-airdrie-echo.svg",
  "Belleville Intelligencer": "/website-logos/pm-belleville-intelligencer.svg",
  "Bow Valley Crag & Canyon": "/website-logos/pm-bow-valley-crag-canyon.svg",

  "Brantford Expositor": "/website-logos/pm-brantford-expositor.svg",
  "Brockville Recorder & Times":
    "/website-logos/pm-brockville-recorder-times.svg",

  "Chatham Daily News": "/website-logos/pm-chatham-daily-news.svg",
  "Chatham This Week": "/website-logos/pm-chatham-this-week.svg",
  "Clinton News Record": "/website-logos/pm-clinton-news-record.svg",
  "Cochrane Times-Post": "/website-logos/pm-cochrane-times-post.svg",
  "Cochrane Times": "/website-logos/pm-cochrane-times.svg",
  "Cold Lake Sun": "/website-logos/pm-cold-lake-sun.svg",
  "Cornwall Standard-Freeholder":
    "/website-logos/pm-cornwall-standard-freeholder.svg",
  "County Market": "/website-logos/pm-county-market.svg",

  "Devon Dispatch": "/website-logos/pm-devon-dispatch.svg",
  "Drayton Valley Western Review":
    "/website-logos/pm-drayton-valley-western-review.svg",
  "Edmonton Examiner": "/website-logos/pm-edmonton-examiner.svg",
  "Elliot Lake Standard": "/website-logos/pm-elliot-lake-standard.svg",
  "Exeter Lakeshore Times Advance":
    "/website-logos/pm-exeter-lakeshore-times-advance.svg",

  "Fairview Post": "/website-logos/pm-fairview-post.svg",
  "Fort Mcmurray Today": "/website-logos/pm-fort-mcmurray-today.svg",
  "Fort Saskatchewan Record": "/website-logos/pm-fort-saskatchewan-record.svg",

  "Gananoque Reporter": "/website-logos/pm-gananoque-reporter.svg",
  "Goderich Signal Star": "/website-logos/pm-goderich-signal-star.svg",
  "Grande Prairie Daily Herald Tribune":
    "/website-logos/pm-grande-prairie-daily-herald-tribune.svg",
  "Grey Bruce This Week": "/website-logos/pm-grey-bruce-this-week.svg",

  "Hanna Herald": "/website-logos/pm-hanna-herald.svg",
  "Hanover Post": "/website-logos/pm-hanover-post.svg",
  "High River Times": "/website-logos/pm-high-river-times.svg",

  "Kenora Miner": "/website-logos/pm-kenora-miner.svg",
  "Kincardine News": "/website-logos/pm-kincardine-news.svg",
  "Kingston/Frontenac This Week":
    "/website-logos/pm-kingston-frontenac-this-week.svg",

  "La Nouvelle Beaumont News":
    "/website-logos/pm-la-nouvelle-beaumont-news.svg",
  "Leduc Representative": "/website-logos/pm-leduc-representative.svg",
  "Lucknow Sentinel": "/website-logos/pm-lucknow-sentinel.svg",

  "Mayerthorpe Freelancer": "/website-logos/pm-mayerthorpe-freelancer.svg",
  "Melfort Journal": "/website-logos/pm-melfort-journal.svg",
  "Mid-North Monitor": "/website-logos/pm-mid-north-monitor.svg",
  "Mitchell Advocate": "/website-logos/pm-mitchell-advocate.svg",
  "Nanton News": "/website-logos/pm-nanton-news.svg",
  "Nipawin Journal": "/website-logos/pm-nipawin-journal.svg",
  "North Bay Nugget": "/website-logos/pm-north-bay-nugget.svg",
  "Northern News": "/website-logos/pm-northern-news.svg",

  "Owen Sound Sun Times": "/website-logos/pm-owen-sound-sun-times.svg",
  "Peace River Record Gazette":
    "/website-logos/pm-peace-river-record-gazette.svg",
  "Pembroke Observer": "/website-logos/pm-pembroke-observer.svg",
  "Pincher Creek Echo": "/website-logos/pm-pincher-creek-echo.svg",

  "Sarnia & Lambton County This Week":
    "/website-logos/pm-sarnia-lambton-county-this-week.svg",
  "Sault Star": "/website-logos/pm-sault-star.svg",
  "Sault This Week": "/website-logos/pm-sault-this-week.svg",
  "Seaforth Huron Expositor": "/website-logos/pm-seaforth-huron-expositor.svg",

  "Sherwood Park News": "/website-logos/pm-sherwood-park-news.svg",
  "Simcoe Reformer": "/website-logos/pm-simcoe-reformer.svg",
  "Spruce Grove Examiner": "/website-logos/pm-spruce-grove-examiner.svg",
  "St. Thomas Times-Journal": "/website-logos/pm-st-thomas-times-journal.svg",

  "Stony Plain Reporter": "/website-logos/pm-stony-plain-reporter.svg",
  "Strathroy Age Dispatch": "/website-logos/pm-strathroy-age-dispatch.svg",
  "Sudbury Star": "/website-logos/pm-sudbury-star.svg",
  "The Community Press": "/website-logos/pm-the-community-press.svg",

  "The County Weekly News": "/website-logos/pm-the-county-weekly-news.svg",
  "The Daily Press": "/website-logos/pm-the-daily-press.svg",
  "The Graphic Leader": "/website-logos/pm-the-graphic-leader.svg",
  "The Kingston Whig Standard":
    "/website-logos/pm-the-kingston-whig-standard.svg",

  "The Londoner": "/website-logos/pm-the-londoner.svg",
  "The Napanee Guide": "/website-logos/pm-the-napanee-guide.svg",
  "The Paris Star": "/website-logos/pm-the-paris-star.svg",
  "The Peace Country Sun": "/website-logos/pm-the-peace-country-sun.svg",

  "The Sarnia Observer": "/website-logos/pm-the-sarnia-observer.svg",
  "The Shoreline Beacon": "/website-logos/pm-the-shoreline-beacon.svg",
  "The Stratford Beacon Herald":
    "/website-logos/pm-the-stratford-beacon-herald.svg",

  "The West Elgin Chronicle": "/website-logos/pm-the-west-elgin-chronicle.svg",

  "The Woodstock Sentinel Review":
    "/website-logos/pm-the-woodstock-sentinel-review.svg",
  "Tillsonburg News": "/website-logos/pm-tillsonburg-news.svg",
  "Timmins Times": "/website-logos/pm-timmins-times.svg",
  "Today's Farmer": "/website-logos/pm-todays-farmer.svg",

  "Trenton Trentonian": "/website-logos/pm-trenton-trentonian.svg",
  "Vermilion Standard": "/website-logos/pm-vermilion-standard.svg",
  "Vulcan Advocate": "/website-logos/pm-vulcan-advocate.svg",

  "Wallaceburg Courier Press":
    "/website-logos/pm-wallaceburg-courier-press.svg",

  "Wetaskiwin Times": "/website-logos/pm-wetaskiwin-times.svg",
  "Whitecourt Star": "/website-logos/pm-whitecourt-star.svg",
  "Wiarton Echo": "/website-logos/pm-wiarton-echo.svg",
  "The Porterville Recorder": "/website-logos/porterville-recorder.png",

  Postmedia: "/website-logos/postmedia.jpg",
  "Premium Feed & Grain": "/website-logos/premiumfeedgrain.png",
  "Press-Telegram": "/website-logos/press-telegram.svg",

  "Pro Ag Farmers Co-op": "/website-logos/proagfarmers.png",

  "The Prospector Resource Investment News":
    "/website-logos/prospector-news.png",
  "Punkin Center Gin": "/website-logos/punkincentergin.png",
  Quotemedia: "/website-logos/quotemedia.png",
  "Remsen Farmers Coop": "/website-logos/remsencoop.png",

  "Rickett Grain Co.": "/website-logos/rickett-grain.jpg",
  "Ringneck Energy": "/website-logos/ringneckenergy.png",
  "Rolling Acres Farm - Canada": "/website-logos/rollingacresgrain.png",
  "Rolling Hills Gin": "/website-logos/rollinghillsgin.png",

  bentoncourier: "/website-logos/saline-courier.png",

  "SanAnselmo.com": "/website-logos/san-anselmo.png",
  "Star Tribune": "/website-logos/san-diego-tribune.svg",

  "SanRafael.com": "/website-logos/san-rafael.jpg",

  "S & B Cattle Company": "/website-logos/sandbcattle.png",
  "SantaClara.com": "/website-logos/santa-clara.png",
  "Santa Maria Times": "/website-logos/santa-maria-times.png",
  "Sargeant Grain Co.": "/website-logos/sargeantgrain.png",
  "Sausalito.com": "/website-logos/sausalito.png",
  "Schramm Feedlot": "/website-logos/schrammfeedlot.jpg",
  Sentieo: "/website-logos/sentieo.png",
  "Schlabs Hysinger": "/website-logos/shcommodities.png",
  "The Globe and Mail": "/website-logos/globeandmail.png",

  "SilverEdge Cooperative": "/website-logos/silveredgecoop.jpg",
  "Farmers Coop Association - Snyder, OK":
    "/website-logos/snyder-farmers-coop.jpg",
  "Sowega Cotton Gin & Warehouse, LLC.": "/website-logos/sowegacotton.png",

  "Spoke.com": "/website-logos/spoke.png",
  "Stafford County Flour Mills": "/website-logos/stafford.jpg",

  "Star Tribune": "/website-logos/star-tribune.svg",
  "Stickney Coop Elevator": "/website-logos/stickney-coop.jpg",
  Stockhouse: "/website-logos/stockhouse.jpg",
  "Stone Station Elevator": "/website-logos/stonestationelevator.png",

  "Stoneybrook Elevators": "/website-logos/stoneybrookelevators.png",
  "Strauss Feedmill / MPS Egg Farms": "/website-logos/straussfeedmill.jpg",

  "Sunnyvale.com": "/website-logos/sunnyvale.gif",
  "Tamar Securities": "/website-logos/tamar-securities.jpg",

  "Tri-Cities Grain, LLC.": "/website-logos/tcgrain.png",
  Teletrader: "/website-logos/teletrader.png",
  "Texas Producers Cooperative": "/website-logos/texasproducerscoop.jpg",
  "Appeal-Democrat": "/website-logos/the-appeal-democrat.png",

  "Kelowna Daily Courier": "/website-logos/the-daily-courier.gif",

  "The Newport Daily Express": "/website-logos/the-newport-daily-express.jpg",
  "The Sun Chronicle": "/website-logos/the-sun-chronicle.png",
  "The Union Democrat": "/website-logos/the-union-democrat.png",

  "The Westerly Sun": "/website-logos/the-westerly-sun.png",
  "The Farmers Elevator Grain & Supply Assn.":
    "/website-logos/thefarmerselevator.png",
  "The Insurance Shop, Inc.": "/website-logos/theinsuranceshopinc.png",
  "Thomson Reuters Newsroom and Terminals":
    "/website-logos/thomson-reuters.png",
  "Times-Herald": "/website-logos/times-herald.png",
  "Townhall Finance": "/website-logos/townhall-finance.png",
  "Tremont Co-operative Grain Co.": "/website-logos/tremont.png",

  "Triple-M-Farms": "/website-logos/triplemfarms.png",
  "Trotter, Inc.": "/website-logos/trotterinc.png",
  "Turner Seed Inc.": "/website-logos/turnerseedinc.png",
  "Turon Mill & Elevator, Inc.": "/website-logos/turonmill.png",
  "Underwood Grain Limited": "/website-logos/underwood-grain.jpg",

  "usa-update.com": "/website-logos/usa-update.png",
  "usanew.biz": "/website-logos/usanew-biz.png",
  "Uvalde County Farmers Coop": "/website-logos/uvaldecoop.png",
  "Value Investing News": "/website-logos/value-investing-news.png",

  "Waitt Grain Co": "/website-logos/waittgrain.png",
  WallStreetSelect: "/website-logos/wall-street-select.gif",
  "WalnutCreekGuide.com": "/website-logos/walnut-creet.png",
  "Walters Co-op Elevator Assn": "/website-logos/walterscoop.png",

  WAOW: "/website-logos/waow.png",
  WBNG: "/website-logos/wbng.png",
  "WEEK/HOIABC": "/website-logos/week.png",
  "Western Cooperative Company": "/website-logos/westco.png",

  WGEM: "/website-logos/wgem.png",
  "WhatBiz.com": "/website-logos/whatbiz.png",
  "Winslow, Evans & Crocker": "/website-logos/winslow.png",
  WKOW: "/website-logos/wkow.png",
  WPTA: "/website-logos/wpta21.png",
  WQOW: "/website-logos/wqow.png",
  WRAL: "/website-logos/wral.jpg",
  WREX: "/website-logos/wrex.png",
  WSIL: "/website-logos/wsiltv.png",

  "Wall Street Journal": "/website-logos/wsj.jpg",
  WVVA: "/website-logos/wvva.png",
  WXOW: "/website-logos/wxow.png",
  X: "/website-logos/x.jpg",
  "xdzee.com": "/website-logos/xdzee.png",
  "YahooFinance Canada": "/website-logos/yahoo-cda.jpg",
  YahooFinance: "/website-logos/yahoo.png",
  "Shelby Daily Globe": "/website-logos/shelby-daily-globe.png",
};

export const orderMapping = {
  // Top priority brands (user's preferred order)
  YahooFinance: "YahooFinance",

  Business_Insider: "Business Insider",
  The_Globe_and_Mail: "The Globe and Mail",
  Barchart_com: "Barchart.com",
  Benzinga: "Benzinga",
  Digital_Journal: "Digital Journal",
  Marketwatch: "Marketwatch",
  Associated_Press: "Associated Press",
  CEO_CA: "CEO.CA",
  National_Post: "National Post",
  Financial_Post: "Financial Post",
  StreetInsider_com: "StreetInsider.com",
  Vancouver_Sun: "Vancouver Sun",
  The_Province: "The Province",
  Toronto_Sun: "Toronto Sun",
  Ottawa_Citizen: "Ottawa Citizen",
  Calgary_Herald: "Calgary Herald",
  Montreal_Gazette: "Montreal Gazette",
  Calgary_Sun: "Calgary Sun",
  Canada_com: "Canada.com",
  Canoe_com: "Canoe.com",
  Central_Charts: "Central Charts",
  Edmonton_Journal: "Edmonton Journal",
  Edmonton_Sun: "Edmonton Sun",
  London_Free_Press: "London Free Press",
  Ottawa_Sun: "Ottawa Sun",
  Regina_Leader_Post: "Regina Leader Post",
  Saskatoon_Star_Phoenix: "Saskatoon Star Phoenix",
  Windsor_Star: "Windsor Star",
  Winnipeg_Sun: "Winnipeg Sun",
  Newsfile: "Newsfile",
  FinanzNachrichten: "FinanzNachrichten",
  X: "X",
  Wall_Street_Journal: "Wall Street Journal",
  Ontario_Farmer: "Ontario Farmer",
  Prince_George_Post: "Prince George Post",
  Airdrie_Echo: "Airdrie Echo",
  Belleville_Intelligencer: "Belleville Intelligencer",
  Bow_Valley_Crag_Canyon: "Bow Valley Crag & Canyon",
  Brantford_Expositor: "Brantford Expositor",
  Brockville_Recorder_Times: "Brockville Recorder & Times",
  Chatham_Daily_News: "Chatham Daily News",
  Chatham_This_Week: "Chatham This Week",
  Clinton_News_Record: "Clinton News Record",
  Cochrane_Times_Post: "Cochrane Times-Post",
  Cochrane_Times: "Cochrane Times",
  Cold_Lake_Sun: "Cold Lake Sun",
  Cornwall_Standard_Freeholder: "Cornwall Standard-Freeholder",
  County_Market: "County Market",
  Devon_Dispatch: "Devon Dispatch",
  Drayton_Valley_Western_Review: "Drayton Valley Western Review",
  Edmonton_Examiner: "Edmonton Examiner",
  Elliot_Lake_Standard: "Elliot Lake Standard",
  Exeter_Lakeshore_Times_Advance: "Exeter Lakeshore Times Advance",
  Fairview_Post: "Fairview Post",
  Fort_Mcmurray_Today: "Fort Mcmurray Today",
  Fort_Saskatchewan_Record: "Fort Saskatchewan Record",
  Gananoque_Reporter: "Gananoque Reporter",
  Goderich_Signal_Star: "Goderich Signal Star",
  Grande_Prairie_Daily_Herald_Tribune: "Grande Prairie Daily Herald Tribune",
  Grey_Bruce_This_Week: "Grey Bruce This Week",
  Hanna_Herald: "Hanna Herald",
  Hanover_Post: "Hanover Post",
  High_River_Times: "High River Times",
  Kenora_Miner: "Kenora Miner",
  Kincardine_News: "Kincardine News",
  Kingston_Frontenac_This_Week: "Kingston/Frontenac This Week",
  La_Nouvelle_Beaumont_News: "La Nouvelle Beaumont News",
  Leduc_Representative: "Leduc Representative",
  Lucknow_Sentinel: "Lucknow Sentinel",
  Mayerthorpe_Freelancer: "Mayerthorpe Freelancer",
  Melfort_Journal: "Melfort Journal",
  Mid_North_Monitor: "Mid-North Monitor",
  Mitchell_Advocate: "Mitchell Advocate",
  Nanton_News: "Nanton News",
  Nipawin_Journal: "Nipawin Journal",
  North_Bay_Nugget: "North Bay Nugget",
  Northern_News: "Northern News",
  Owen_Sound_Sun_Times: "Owen Sound Sun Times",
  Peace_River_Record_Gazette: "Peace River Record Gazette",
  Pembroke_Observer: "Pembroke Observer",
  Pincher_Creek_Echo: "Pincher Creek Echo",
  Sarnia_Lambton_County_This_Week: "Sarnia & Lambton County This Week",
  Sault_Star: "Sault Star",
  Sault_This_Week: "Sault This Week",
  Seaforth_Huron_Expositor: "Seaforth Huron Expositor",
  Sherwood_Park_News: "Sherwood Park News",
  Simcoe_Reformer: "Simcoe Reformer",
  Spruce_Grove_Examiner: "Spruce Grove Examiner",
  St_Thomas_Times_Journal: "St. Thomas Times-Journal",
  Stony_Plain_Reporter: "Stony Plain Reporter",
  Strathroy_Age_Dispatch: "Strathroy Age Dispatch",
  Sudbury_Star: "Sudbury Star",
  The_Community_Press: "The Community Press",
  The_County_Weekly_News: "The County Weekly News",
  The_Daily_Press: "The Daily Press",
  The_Graphic_Leader: "The Graphic Leader",
  The_Kingston_Whig_Standard: "The Kingston Whig Standard",
  The_Londoner: "The Londoner",
  The_Napanee_Guide: "The Napanee Guide",
  The_Paris_Star: "The Paris Star",
  The_Peace_Country_Sun: "The Peace Country Sun",
  The_Sarnia_Observer: "The Sarnia Observer",
  The_Shoreline_Beacon: "The Shoreline Beacon",
  The_Stratford_Beacon_Herald: "The Stratford Beacon Herald",
  The_West_Elgin_Chronicle: "The West Elgin Chronicle",
  The_Woodstock_Sentinel_Review: "The Woodstock Sentinel Review",
  Tillsonburg_News: "Tillsonburg News",
  Timmins_Times: "Timmins Times",
  Today_S_Farmer: "Today'S Farmer",
  Trenton_Trentonian: "Trenton Trentonian",
  Vermilion_Standard: "Vermilion Standard",
  Vulcan_Advocate: "Vulcan Advocate",
  Wallaceburg_Courier_Press: "Wallaceburg Courier Press",
  Wetaskiwin_Times: "Wetaskiwin Times",
  Whitecourt_Star: "Whitecourt Star",
  Wiarton_Echo: "Wiarton Echo",
  Big_Spring_Herald: "Big Spring Herald",
  Daily_Times_Leader: "Daily Times Leader",
  Decatur_Daily_Democrat: "Decatur Daily Democrat",
  Deer_Park_Tribune: "Deer Park Tribune",
  Inyo_Register: "Inyo Register",
  Kane_Republican: "Kane Republican",
  Mammoth_Times: "Mammoth Times",
  Minster_Community_Post: "Minster Community Post",
  Observer_News_Enterprise: "Observer News Enterprise",
  Poteau_Daily_News: "Poteau Daily News",
  The_Punxsutawney_Spirit: "The Punxsutawney Spirit",
  Ridgway_Record: "Ridgway Record",
  Starkville_Daily_News: "Starkville Daily News",
  Sweetwater_Reporter: "Sweetwater Reporter",
  The_Antlers_American: "The Antlers American",
  The_Evening_Leader: "The Evening Leader",
  The_Pilot_News: "The Pilot News",
  Valley_City_Times_Record: "Valley City Times-Record",
  Wapakoneta_Daily_News: "Wapakoneta Daily News",
  The_Chronicle_Journal: "The Chronicle Journal",
  Antelope_Valley_Press: "Antelope Valley Press",
  Bakersfield_com: "Bakersfield.com",
  Bingham_News_Chronicle: "Bingham News Chronicle",
  Borger_News_Herald: "Borger News-Herald",
  Boston_Herald: "Boston Herald",
  BPAS: "BPAS",
  The_Buffalo_News: "The Buffalo News",
  Burlingame_com: "Burlingame.com",
  CorteMadera_com: "CorteMadera.com",
  Custer_County_Chief: "Custer County Chief",
  DalyCity_com: "DalyCity.com",
  Fat_Pitch_Financials: "Fat Pitch Financials",
  "1st_Discount_Brokerage": "1st Discount Brokerage",
  FWNBC: "FWNBC",
  fox47: "fox47",
  Franklin_Credit_Management_Corporation:
    "Franklin Credit Management Corporation",
  Great_American_Advisors: "Great American Advisors",
  Hannibal_Courier_Post: "Hannibal Courier - Post",
  Herald_Whig: "Herald-Whig",
  International_Business_Times: "International Business Times",
  Imperial_Valley_Press: "Imperial Valley Press",
  KBJR_CBS3: "KBJR/CBS3",
  KTIV: "KTIV",
  KTTC: "KTTC",
  KVOA: "KVOA",
  KWWL: "KWWL",
  Livermore_com: "Livermore.com",
  lodinews_com: "lodinews.com",
  LosAltos_com: "LosAltos.com",
  Malvern_Daily_Record: "Malvern Daily Record",
  MenloPark_com: "MenloPark.com",
  MillValley_com: "MillValley.com",
  Millennium_Trust_Company: "Millennium Trust Company",
  myMotherLode_com_California_Gold_Country:
    "myMotherLode.com California Gold Country",
  NewsOK: "NewsOK",
  Penticton_Herald: "Penticton Herald",
  Pittsburgh_Post_Gazette: "Pittsburgh Post-Gazette",
  Pleasanton_com: "Pleasanton.com",
  The_Porterville_Recorder: "The Porterville Recorder",
  Press_Telegram: "Press-Telegram",
  Benton_Courier: "Benton Courier",
  SanAnselmo_com: "SanAnselmo.com",
  Sign_On_San_Diego: "Sign On San Diego",
  SanRafael_com: "SanRafael.com",
  SantaClara_com: "SantaClara.com",
  Santa_Maria_Times: "Santa Maria Times",
  Sausalito_com: "Sausalito.com",
  Shelby_Daily_Globe: "Shelby Daily Globe",
  Spoke_com: "Spoke.com",
  Star_Tribune: "Star Tribune",
  Sunnyvale_com: "Sunnyvale.com",
  Tamar_Securities: "Tamar Securities",
  Appeal_Democrat: "Appeal-Democrat",
  Kelowna_Daily_Courier: "Kelowna Daily Courier",
  The_Newport_Daily_Express: "The Newport Daily Express",
  The_Sun_Chronicle: "The Sun Chronicle",
  The_Union_Democrat: "The Union Democrat",
  The_Westerly_Sun: "The Westerly Sun",
  Times_Herald: "Times-Herald",
  Townhall_Finance: "Townhall Finance",
  Value_Investing_News: "Value Investing News",
  WallStreetSelect: "WallStreetSelect",
  WalnutCreekGuide_com: "WalnutCreekGuide.com",
  WAOW: "WAOW",
  WBNG: "WBNG",
  WEEK_HOIABC: "WEEK/HOIABC",
  WGEM: "WGEM",
  Winslow_Evans_Crocker: "Winslow, Evans & Crocker",
  WKOW: "WKOW",
  WPTA: "WPTA",
  WQOW: "WQOW",
  WRAL: "WRAL",
  WREX: "WREX",
  WSIL: "WSIL",
  WVVA: "WVVA",
  WXOW: "WXOW",
  OFOR: "OFOR",
  A_M_Bickley_Inc: "A.M. Bickley Inc.",
  Bieri_Grain_LLC: "Bieri Grain, LLC",
  Burlington_Cooperative_Association: "Burlington Cooperative Association",
  Gard_Trading_Services_Farmers_View: "Gard Trading Services (Farmers View)",
  Flatlands_Grain: "Flatlands Grain",
  Gerald_Grain_Center: "Gerald Grain Center",
  "7_Rivers_Livestock": "7 Rivers Livestock",
  AgBest_Cooperative_Inc: "AgBest Cooperative Inc.",
  AgRail_LLC: "AgRail LLC ",
  AGrowStar: "AGrowStar",
  Ag_Southwest_Crop_Ranch_Insurance: "Ag Southwest Crop & Ranch Insurance",
  Anton_Co_op: "Anton Co-op",
  Arabi_Gin: "Arabi Gin",
  Augusta_Farmers_Coop: "Augusta Farmers Coop",
  Banner_Co_operative_Elevator_Association:
    "Banner Co-operative Elevator Association",
  Bar_G_Feedyard: "Bar-G Feedyard",
  Beardsley_Farmers_Elevator_Company: "Beardsley Farmers Elevator Company",
  Bloomington_Livestock_Exchange: "Bloomington Livestock Exchange",
  Bolt_Marketing_LLC: "Bolt Marketing LLC",
  BRT_AG_TURF: "BRT AG & TURF",
  Butterfield_Associates_Grain: "Butterfield & Associates Grain",
  Cain_Agra: "Cain Agra",
  Cameron_Grain_Corporation: "Cameron Grain Corporation",
  CDR_Farms_LLC: "CDR Farms, LLC",
  Central_Plains_Trading: "Central Plains Trading",
  Cooperative_Grain_and_Supply: "Cooperative Grain and Supply",
  Cherokee_Gin_Cotton_Co: "Cherokee Gin & Cotton Co. ",
  Clare_Mar_Farms_Limited: "Clare-Mar Farms Limited",
  CO_OP_Services_Inc: "CO-OP Services, Inc.",
  Cunningham_Farms_Inc: "Cunningham Farms, Inc.",
  Dacoma_Farmers_Coop: "Dacoma Farmers Coop",
  Dixon_Gin_Co_Inc: "Dixon Gin Co., Inc.",
  Doerun_Gin_Company: "Doerun Gin Company",
  Doon_Elevator_Inc: "Doon Elevator, Inc",
  Dumas_Co_op_Elevators: "Dumas Co-op Elevators",
  Dummer_s_Grain_Service_Buck_County_Grain:
    "Dummer&#39;s Grain Service & Buck County Grain",
  Edon_Farmers_Co_op: "Edon Farmers Co-op",
  Farmers_Cooperative_Association_of_Eldorado:
    "Farmers Cooperative Association of Eldorado",
  Farmers_Coop_Mill_and_Elevator_Carnegie:
    "Farmers Coop Mill and Elevator - Carnegie",
  Litchfield_Farmers_Grain: "Litchfield Farmers Grain",
  Farmers_Cooperative_Elevator_Co_MN_Hanley_Falls:
    "Farmers Cooperative Elevator Co. MN Hanley Falls",
  Farmers_Exchange: "Farmers Exchange",
  Farmers_Grain_Elevator: "Farmers Grain Elevator",
  French_Camp_Grain_Company_Inc: "French Camp Grain Company, Inc.",
  Glendenning_Grain: "Glendenning Grain",
  Farmers_Cooperative_Association_Tonkawa_OK:
    "Farmers Cooperative Association - Tonkawa, OK",
  Gowanlea_LTD: "Gowanlea LTD.",
  Green_City_Livestock_Marketing_LLC: "Green City Livestock Marketing, LLC",
  H_B_Specialties_Inc: "H & B Specialties, Inc.",
  Hull_Feed_Produce_Inc: "Hull Feed & Produce, Inc",
  InterMountain_Beef: "InterMountain Beef",
  Investors_Commodity_Services: "Investors Commodity Services",
  James_Valley_Grain_LLC: "James Valley Grain, LLC",
  J_LYN_Grains: "J-LYN Grains",
  Judge_Farms: "Judge Farms",
  Keller_Grain: "Keller Grain",
  Lang_Farms_Ltd: "Lang Farms, Ltd.",
  LeRoy_Coop: "LeRoy Coop",
  Les_Young_Farms_Ltd: "Les Young Farms Ltd",
  Lick_Elevator_Inc: "Lick Elevator Inc.",
  Little_Sioux_Corn_Processors: "Little Sioux Corn Processors",
  Lubbock_Feeders: "Lubbock Feeders",
  McCune_Farmers_Union_Coop_Association:
    "McCune Farmers Union Coop Association",
  Melrose_Farm_Service_Inc: "Melrose Farm Service Inc",
  Mid_Columbia_Insurance_Inc: "Mid-Columbia Insurance Inc.",
  Mid_Valley_Cotton_Growers_Inc: "Mid-Valley Cotton Growers, Inc.",
  Mobley_Gin_Company: "Mobley Gin Company",
  Montrose_Grain_and_Supply_LLC: "Montrose Grain and Supply, LLC",
  Farmers_Coop_Elevator_Morganville_Coop:
    "Farmers Coop Elevator - Morganville Coop",
  Mulvane_Cooperative_Union: "Mulvane Cooperative Union",
  Northwest_Investments: "Northwest Investments",
  Offerle_Cooperative_Grain_Supply_Company:
    "Offerle Cooperative Grain & Supply Company",
  Land_Run_Farmers_Cooperative_OK: "Land Run Farmers Cooperative - OK",
  Omega_Farm_Supply_Inc_Gin_Company: "Omega Farm Supply, Inc. & Gin Company",
  Parrish_Shop_Sales_LLC: "Parrish Shop & Sales LLC",
  PCE_Producers_Coop_Elevator: "PCE Producers Coop Elevator",
  Petersen_Custom_Farming: "Petersen Custom Farming",
  Pilot_Grove_Elevator_Cooperative_Inc:
    "Pilot Grove Elevator Cooperative, Inc.",
  Premium_Feed_Grain: "Premium Feed & Grain",
  Pro_Ag_Farmers_Co_op: "Pro Ag Farmers Co-op",
  Punkin_Center_Gin: "Punkin Center Gin",
  Remsen_Farmers_Coop: "Remsen Farmers Coop",
  Rickett_Grain_Co: "Rickett Grain Co.",
  Ringneck_Energy: "Ringneck Energy",
  Rolling_Acres_Farm_Canada: "Rolling Acres Farm - Canada",
  Rolling_Hills_Gin: "Rolling Hills Gin",
  S_B_Cattle_Company: "S & B Cattle Company",
  Sargeant_Grain_Co: "Sargeant Grain Co.",
  Schramm_Feedlot: "Schramm Feedlot",
  Schlabs_Hysinger: "Schlabs Hysinger",
  SilverEdge_Cooperative: "SilverEdge Cooperative",
  Farmers_Coop_Association_Snyder_OK: "Farmers Coop Association - Snyder, OK",
  Sowega_Cotton_Gin_Warehouse_LLC: "Sowega Cotton Gin & Warehouse, LLC.",
  Stafford_County_Flour_Mills: "Stafford County Flour Mills",
  Stickney_Coop_Elevator: "Stickney Coop Elevator",
  Stone_Station_Elevator: "Stone Station Elevator",
  Stoneybrook_Elevators: "Stoneybrook Elevators",
  Strauss_Feedmill_MPS_Egg_Farms: "Strauss Feedmill / MPS Egg Farms",
  Tri_Cities_Grain_LLC: "Tri-Cities Grain, LLC.",
  Texas_Producers_Cooperative: "Texas Producers Cooperative",
  The_Farmers_Elevator_Grain_Supply_Assn:
    "The Farmers Elevator Grain & Supply Assn.",
  The_Insurance_Shop_Inc: "The Insurance Shop, Inc.",
  Tremont_Co_operative_Grain_Co: "Tremont Co-operative Grain Co.",
  Triple_M_Farms: "Triple-M-Farms",
  Trotter_Inc: "Trotter, Inc.",
  Turner_Seed_Inc: "Turner Seed Inc.",
  Turon_Mill_Elevator_Inc: "Turon Mill & Elevator, Inc.",
  Underwood_Grain_Limited: "Underwood Grain Limited",
  Uvalde_County_Farmers_Coop: "Uvalde County Farmers Coop",
  Waitt_Grain_Co: "Waitt Grain Co",
  Walters_Co_op_Elevator_Assn: "Walters Co-op Elevator Assn",
  Western_Cooperative_Company: "Western Cooperative Company",

  // Additional outlets not in the main list
  CRWE_World: "CRWE World",
  Thomson_Reuters_Newsroom_and_Terminals:
    "Thomson Reuters Newsroom and Terminals",
  Apple_News: "Apple News",
  YahooFinance_Canada: "YahooFinance Canada",
  Gale_Cengage_Learning: "Gale Cengage Learning",
  accern: "accern",
  Stockhouse: "Stockhouse",
  Newstex: "Newstex",
  The_Prospector_Resource_Investment_News:
    "The Prospector Resource Investment News",
  Dow_Jones_Newswires: "Dow Jones Newswires",
  Dow_Jones_Factiva: "Dow Jones Factiva",
  Sentieo: "Sentieo",
  Comtex: "Comtex",
  Newsbank: "Newsbank",
  InfoDesk: "InfoDesk",
  INK_Research: "INK Research",
  Teletrader: "Teletrader",
  Moody_s_Analytics_NewsEdge: "Moody's Analytics NewsEdge",
  Newsware: "Newsware",
  Quotemedia: "Quotemedia",
  Postmedia: "Postmedia",
  Bloomberg_Website: "Bloomberg Website",
  Lexis_Nexis: "Lexis Nexis",
  Ad_Hoc_News: "Ad Hoc News",
  beautytipa_com: "beautytipa.com",
  creatework_com: "creatework.com",
  eco_natur_com: "eco-natur.com",
  fitnesseditors_com: "fitnesseditors.com",
  motor_world_com: "motor-world.com",
  usa_update_com: "usa-update.com",
  usanew_biz: "usanew.biz",
  whatbiz_co: "whatbiz.co",
  xdzee_com: "xdzee.com",
};
